title: compl[:sparkles:]nce
description: Alle informatie over verantwoord AI gebruik in de publieke sector
theme: just-the-docs

url: https://j3vh.github.io/aicompdocs
favicon_ico: "/assets/images/favicon.ico"

plugins:
  - jemoji


#aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "10.2.4"
